name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  add-label:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.title, 'firefight')
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "automerge"
          color: "0000ff"
  automerge:
    runs-on: ubuntu-latest
    needs: add-label
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.AUTO_MERGE_TOKEN }}"
